language: cpp
sudo: required
dist: trusty

notifications:
  email: false

branches:
  only:
    - master
    - develop

compiler:
  - clang

os:
  - linux

env:
  - CONFIG=Release64

before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install -qq
      build-essential
      clang
      unzip
      xvfb
      libfreetype6-dev
      libx11-dev
      libxinerama-dev
      libxrandr-dev
      libxcursor-dev
      libxcomposite-dev
      mesa-common-dev
      libasound2-dev
      freeglut3-dev
      libcurl4-gnutls-dev+
      libasound2-dev
      libjack-dev
  - pushd ThirdParty
  - wget -w 1 -r -np -nd -nv http://www.steinberg.net/sdk_downloads/vstsdk367_03_03_2017_build_352.zip
  - unzip -qq ./vstsdk367_03_03_2017_build_352.zip
  - pushd VST_SDK
  - ./copy_vst2_to_vst3_sdk.sh 
  - popd
  - popd

install:
  - git submodule update --init --recursive

script:
  - export DISPLAY=localhost:1.0
  - xvfb-run -a bash -c 'cd Projects/LinuxMakefile && make'
