language: cpp
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/ThirdParty/VST_SDK
    - ${TRAVIS_BUILD_DIR}/ThirdParty/ASIO

branches:
  only:
    - master
    - develop
    - fix-travis

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - llvm-3.9-dev    # for LLVMgold.so
            - libc++-dev
            - libfreetype6-dev
            - libx11-dev
            - libxinerama-dev
            - libxrandr-dev
            - libxcursor-dev
            - libxcomposite-dev
            - mesa-common-dev
            - freeglut3-dev
            - libcurl4-gnutls-dev+
            - libasound2-dev
            - libjack-dev
            - unzip
            - xvfb
      env:
        - COMPILER_VER=-3.9
        - CONFIG=Travis
        - DISPLAY=localhost:1.0
        - CFLAGS=-stdlib=libc++
        - LDFLAGS=-stdlib=libc++

before_install:
  - pushd ThirdParty
  - ./get_asio_and_vst_sdks.sh 
  - popd

script:
  - xvfb-run -a bash -c 'cd Projects/LinuxMakefile && make'
