version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2015
configuration: Release 64-bit
platform: x64
clone_depth: 1
install:
- ps: |
    cmd.exe /c 'git submodule update --init --recursive 2> $null'

    $asioSdkSource = "http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip"
    $asioSdkDestination = "ThirdParty\asiosdk2.3.zip"
    Invoke-WebRequest $asioSdkSource -OutFile $asioSdkDestination

    7z x $asioSdkDestination -oThirdParty

    Rename-Item -path ThirdParty\ASIOSDK2.3 -newName ASIO
build:
  project: Projects\VisualStudio2015\Helio.sln
  verbosity: minimal